package QueuedJobsServiceService;
# Generated by SOAP::Lite (v0.710.07) for Perl -- soaplite.com
# Copyright (C) 2000-2006 Paul Kulchenko, Byrne Reese
# -- generated at [Tue Jun  2 10:13:31 2009]
# -- generated from http://ambon.ifa.hawaii.edu:8080/Mleadr/QueuedJobsService?wsdl
my %methods = (
deleteGroup => {
    endpoint => 'http://ambon.ifa.hawaii.edu:8080/Mleadr/QueuedJobsService',
    soapaction => '',
    namespace => 'http://services.ws.mleadr.referentia.com/',
    parameters => [
    ], # end parameters
  }, # end deleteGroup
submitQueuedJob => {
    endpoint => 'http://ambon.ifa.hawaii.edu:8080/Mleadr/QueuedJobsService',
    soapaction => '',
    namespace => 'http://services.ws.mleadr.referentia.com/',
    parameters => [
    ], # end parameters
  }, # end submitQueuedJob
getGroupTables => {
    endpoint => 'http://ambon.ifa.hawaii.edu:8080/Mleadr/QueuedJobsService',
    soapaction => '',
    namespace => 'http://services.ws.mleadr.referentia.com/',
    parameters => [
    ], # end parameters
  }, # end getGroupTables
getGroupSchemas => {
    endpoint => 'http://ambon.ifa.hawaii.edu:8080/Mleadr/QueuedJobsService',
    soapaction => '',
    namespace => 'http://services.ws.mleadr.referentia.com/',
    parameters => [
      SOAP::Data->new(name => 'sessionID', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end getGroupSchemas
createGroup => {
    endpoint => 'http://ambon.ifa.hawaii.edu:8080/Mleadr/QueuedJobsService',
    soapaction => '',
    namespace => 'http://services.ws.mleadr.referentia.com/',
    parameters => [
    ], # end parameters
  }, # end createGroup
submitQuery => {
    endpoint => 'http://ambon.ifa.hawaii.edu:8080/Mleadr/QueuedJobsService',
    soapaction => '',
    namespace => 'http://services.ws.mleadr.referentia.com/',
    parameters => [
      SOAP::Data->new(name => 'sessionID', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'schemaGroup', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'schema', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'query', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end submitQuery
setGroupTableAccess => {
    endpoint => 'http://ambon.ifa.hawaii.edu:8080/Mleadr/QueuedJobsService',
    soapaction => '',
    namespace => 'http://services.ws.mleadr.referentia.com/',
    parameters => [
    ], # end parameters
  }, # end setGroupTableAccess
extractResults => {
    endpoint => 'http://ambon.ifa.hawaii.edu:8080/Mleadr/QueuedJobsService',
    soapaction => '',
    namespace => 'http://services.ws.mleadr.referentia.com/',
    parameters => [
    ], # end parameters
  }, # end extractResults
setGroupUserAccess => {
    endpoint => 'http://ambon.ifa.hawaii.edu:8080/Mleadr/QueuedJobsService',
    soapaction => '',
    namespace => 'http://services.ws.mleadr.referentia.com/',
    parameters => [
    ], # end parameters
  }, # end setGroupUserAccess
getJobs => {
    endpoint => 'http://ambon.ifa.hawaii.edu:8080/Mleadr/QueuedJobsService',
    soapaction => '',
    namespace => 'http://services.ws.mleadr.referentia.com/',
    parameters => [
    ], # end parameters
  }, # end getJobs
cancelJob => {
    endpoint => 'http://ambon.ifa.hawaii.edu:8080/Mleadr/QueuedJobsService',
    soapaction => '',
    namespace => 'http://services.ws.mleadr.referentia.com/',
    parameters => [
    ], # end parameters
  }, # end cancelJob
getOutputFormats => {
    endpoint => 'http://ambon.ifa.hawaii.edu:8080/Mleadr/QueuedJobsService',
    soapaction => '',
    namespace => 'http://services.ws.mleadr.referentia.com/',
    parameters => [
    ], # end parameters
  }, # end getOutputFormats
getUserGroups => {
    endpoint => 'http://ambon.ifa.hawaii.edu:8080/Mleadr/QueuedJobsService',
    soapaction => '',
    namespace => 'http://services.ws.mleadr.referentia.com/',
    parameters => [
    ], # end parameters
  }, # end getUserGroups
getSchemaGroups => {
    endpoint => 'http://ambon.ifa.hawaii.edu:8080/Mleadr/QueuedJobsService',
    soapaction => '',
    namespace => 'http://services.ws.mleadr.referentia.com/',
    parameters => [
      SOAP::Data->new(name => 'sessionID', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end getSchemaGroups
getJobStatus => {
    endpoint => 'http://ambon.ifa.hawaii.edu:8080/Mleadr/QueuedJobsService',
    soapaction => '',
    namespace => 'http://services.ws.mleadr.referentia.com/',
    parameters => [
    ], # end parameters
  }, # end getJobStatus

); # end my %methods

use SOAP::Lite;
use Exporter;
use Carp ();

use vars qw(@ISA $AUTOLOAD @EXPORT_OK %EXPORT_TAGS);
@ISA = qw(Exporter SOAP::Lite);
@EXPORT_OK = (keys %methods);
%EXPORT_TAGS = ('all' => [@EXPORT_OK]);

sub _call {
    my ($self, $method) = (shift, shift);
    my $name = UNIVERSAL::isa($method => 'SOAP::Data') ? $method->name : $method;
    my %method = %{$methods{$name}};
    $self->proxy($method{endpoint} || Carp::croak "No server address (proxy) specified")
        unless $self->proxy;
    my @templates = @{$method{parameters}};
    my @parameters = ();
    foreach my $param (@_) {
        if (@templates) {
            my $template = shift @templates;
            my ($prefix,$typename) = SOAP::Utils::splitqname($template->type);
            my $method = 'as_'.$typename;
            my $result = $self->serializer->$method($param, $template->name, $template->type, $template->attr);
            push(@parameters, $template->value($result->[2]));
        }
        else {
            push(@parameters, $param);
        }
    }
    $self->endpoint($method{endpoint})
       ->ns($method{namespace})
       ->on_action(sub{qq!"$method{soapaction}"!});
    $self->serializer->register_ns("http://www.w3.org/2001/XMLSchema","xsd");
    $self->serializer->register_ns("http://services.ws.mleadr.referentia.com/","tns");
    $self->serializer->register_ns("http://schemas.xmlsoap.org/wsdl/soap/","soap");
    my $som = $self->SUPER::call($method => @parameters);
    if ($self->want_som) {
        return $som;
    }
    UNIVERSAL::isa($som => 'SOAP::SOM') ? wantarray ? $som->paramsall : $som->result : $som;
}

sub BEGIN {
    no strict 'refs';
    for my $method (qw(want_som)) {
        my $field = '_' . $method;
        *$method = sub {
            my $self = shift->new;
            @_ ? ($self->{$field} = shift, return $self) : return $self->{$field};
        }
    }
}
no strict 'refs';
for my $method (@EXPORT_OK) {
    my %method = %{$methods{$method}};
    *$method = sub {
        my $self = UNIVERSAL::isa($_[0] => __PACKAGE__)
            ? ref $_[0]
                ? shift # OBJECT
                # CLASS, either get self or create new and assign to self
                : (shift->self || __PACKAGE__->self(__PACKAGE__->new))
            # function call, either get self or create new and assign to self
            : (__PACKAGE__->self || __PACKAGE__->self(__PACKAGE__->new));
        $self->_call($method, @_);
    }
}

sub AUTOLOAD {
    my $method = substr($AUTOLOAD, rindex($AUTOLOAD, '::') + 2);
    return if $method eq 'DESTROY' || $method eq 'want_som';
    die "Unrecognized method '$method'. List of available method(s): @EXPORT_OK\n";
}

1;
