package AuthServiceService;
# Generated by SOAP::Lite (v0.710.07) for Perl -- soaplite.com
# Copyright (C) 2000-2006 Paul Kulchenko, Byrne Reese
# -- generated at [Mon Jun  1 16:45:30 2009]
# -- generated from file:./AuthServiceService.wsdl
my %methods = (
logout => {
    endpoint => 'http://ps01.pha.jhu.edu:8080/Mleadr/AuthService',
    soapaction => '',
    namespace => 'http://services.ws.mleadr.referentia.com/',
    parameters => [
    ], # end parameters
  }, # end logout
getEnvVar => {
    endpoint => 'http://ps01.pha.jhu.edu:8080/Mleadr/AuthService',
    soapaction => '',
    namespace => 'http://services.ws.mleadr.referentia.com/',
    parameters => [
    ], # end parameters
  }, # end getEnvVar
login => {
    endpoint => 'http://ps01.pha.jhu.edu:8080/Mleadr/AuthService',
    soapaction => '',
    namespace => 'http://services.ws.mleadr.referentia.com/',
    parameters => [
      SOAP::Data->new(name => 'userid', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'password', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end login
); # end my %methods

use SOAP::Lite;
use Exporter;
use Carp ();

use vars qw(@ISA $AUTOLOAD @EXPORT_OK %EXPORT_TAGS);
@ISA = qw(Exporter SOAP::Lite);
@EXPORT_OK = (keys %methods);
%EXPORT_TAGS = ('all' => [@EXPORT_OK]);

sub _call {
    my ($self, $method) = (shift, shift);
    my $name = UNIVERSAL::isa($method => 'SOAP::Data') ? $method->name : $method;
    my %method = %{$methods{$name}};
    $self->proxy($method{endpoint} || Carp::croak "No server address (proxy) specified")
        unless $self->proxy;
    my @templates = @{$method{parameters}};
    my @parameters = ();
    foreach my $param (@_) {
        if (@templates) {
            my $template = shift @templates;
            my ($prefix,$typename) = SOAP::Utils::splitqname($template->type);
            my $method = 'as_'.$typename;
            # TODO - if can('as_'.$typename) {...}
            my $result = $self->serializer->$method($param, $template->name, $template->type, $template->attr);
            push(@parameters, $template->value($result->[2]));
        }
        else {
            push(@parameters, $param);
        }
    }
    $self->endpoint($method{endpoint})
         ->ns($method{namespace})
         ->on_action(sub{qq!"$method{soapaction}"!});
    $self->serializer->register_ns("http://ps01.pha.jhu.edu:8080/Mleadr/AuthService?xsd=1","xsd");
    $self->serializer->register_ns("http://services.ws.mleadr.referentia.com/","tns");
    $self->serializer->register_ns("http://schemas.xmlsoap.org/wsdl/soap/","soap");
    my $som = $self->SUPER::call($method => @parameters);
    if ($self->want_som) {
        return $som;
    }
    UNIVERSAL::isa($som => 'SOAP::SOM') ? wantarray ? $som->paramsall : $som->result : $som;
}

sub BEGIN {
    no strict 'refs';
    for my $method (qw(want_som)) {
        my $field = '_' . $method;
        *$method = sub {
            my $self = shift->new;
            @_ ? ($self->{$field} = shift, return $self) : return $self->{$field};
        }
    }
}
no strict 'refs';
for my $method (@EXPORT_OK) {
    my %method = %{$methods{$method}};
    *$method = sub {
        my $self = UNIVERSAL::isa($_[0] => __PACKAGE__)
            ? ref $_[0]
                ? shift # OBJECT
                # CLASS, either get self or create new and assign to self
                : (shift->self || __PACKAGE__->self(__PACKAGE__->new))
            # function call, either get self or create new and assign to self
            : (__PACKAGE__->self || __PACKAGE__->self(__PACKAGE__->new));
        $self->_call($method, @_);
    }
}

sub AUTOLOAD {
    my $method = substr($AUTOLOAD, rindex($AUTOLOAD, '::') + 2);
    return if $method eq 'DESTROY' || $method eq 'want_som';
    die "Unrecognized method '$method'. List of available method(s): @EXPORT_OK\n";
}

1;
